version: "3"
services:
  sum-server:
    image: sum-server
    deploy:
      replicas: 10
      resources: 
        limits: 
          cpus: "0.2"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "7777:7777"
    networks:
      - sum-server-net
networks:
  sum-server-net: